version: "3.3"
services:
  redis:
    image: redis:7.0.15
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - redis_volume_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379