version: "3.3"
services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017 
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7.0.15
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - redis_volume_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: